Fixed main workflow IM SORRY LEWIS I AM!

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -5,12 +5,6 @@ on:
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
-  # Triggers the workflow on push request events but only for the main branch
-  push:
-    branches:
-      - main
-      - development
-      
   # Additional trigger for increased verbosity
   workflow_run:
     workflows: [Run Tests]
@@ -22,9 +16,23 @@ on:
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "SFTP"
+  check-test-results:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check Test Failure
+        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
+        run: |
+          echo 'Tests have failed.'
+          exit 1
+
+      - name: Check Test Success
+        if: ${{ github.event.workflow_run.conclusion == 'success' }}
+        run: |
+          echo 'Tests were successful.'
+
   deploy-via-sftp:
     runs-on: ubuntu-latest
+    if: ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v2
@@ -40,12 +48,12 @@ jobs:
           ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
 
           # will put all file under this path
-          local_path: ./# default is ./*
+          local_paths: |
+            ./public_html
+            ./WoodLess
+
           # files will copy to under remote_path
           remote_path: ./
 
           # sftp args
           args: '-o ConnectTimeout=5'
-
-
-          
